### ISSUE TITLE
Question regarding the syntax of a list of named scalars

### ISSUE THREAD

**Issue by v217** [ConradIrwin/zed-extension-conl#1]
Thank you for CONL!

Only one glance at the YAML spec makes the value of the simplicity of your syntax proposal obvious!

Question: What's the syntax of a list of named scalars? The first option doesn't seem to be recognized.

Thanks!

![image](https://github.com/user-attachments/assets/77799a2b-c6f0-4afb-b7d5-0520e9a7ca4a)

**Comment by v217** [comment]
I did forget the following option.
So a list of one element would be the same as a scalar value?
![image](https://github.com/user-attachments/assets/5f6bc5b7-74c0-476c-bfb5-4c3204524611)

**Comment by ConradIrwin** [comment]
Excited to see someone else using this!

There's no real concept of "named scalars", CONL maps to a JSON-like structure so you can have scalars, maps and lists.

If you want something like `[{"key1": "value1"},{"key2":"value2"}]` in JSON, then your second option gives you that; but if you want something like `{"key1":"value1", "key2":"value2"}` then you want the third option.

I was initially on the fence about allowing the first option too. But URLs used in configuration files frequently contain `=`, and I didn't want to require quoting them. Supporting the shorter syntax also introduces a question of "what does `= key1 = value1 = value2` mean?

**Comment by v217** [comment]
Oh, I see, so the example is valid, because you can interpret the "file border" as map?

**Comment by v217** [comment]
Or in other words, the contents of the file in the example is the content of a map?

**Comment by ConradIrwin** [comment]
Yes, the whole file is treated as a map.

**Comment by v217** [comment]
Thank you for your fast and clarifying response!
I will use CONL for note-taking. It's really a pleasure to not bother about a myriad of complicated quoting rules (e.g.: https://yaml-multiline.info/). What would be great would be a short  EBNF grammar and command line JSON-CONL translator, so people can get familiar with the syntax!
Thank you again for your fast response! I am really happy to have found this project!

**Comment by ConradIrwin** [comment]
Great!

Yes, I have plans to build those (and I guess I should make myself a landing page to run them too :D).
